### ISSUE TITLE
Use docker name instead of container id in logs and metrics

### ISSUE THREAD

**Issue by ateska** [TeskaLabs/asab#123]
When operating ASAB microservice in the docker, the docker container id (from a hostname) is used for logging and metrics.
It will be much more readable when container name is used.

**Comment by ateska** [comment]
The main question is, how to access Docker container names from within the Docker container itself.

**Comment by ateska** [comment]
https://stackoverflow.com/questions/56675083/getting-the-name-of-the-container-from-within-the-container/56682693#56682693

**Comment by PremyslCerny** [comment]
One option to resolve the issue uses Docker Remote API, which can be enabled in docker.service configuration file using this guide:
https://medium.com/@ssmak/how-to-enable-docker-remote-api-on-docker-host-7b73bd3278c6

Then inside the container, the remote API can be access, using hostname/ip of the host computer, via APi call:

```
curl -s lm1:2377/containers/$HOSTNAME/json | jq -r ".Name"
```

More information: https://stackoverflow.com/questions/56675083/getting-the-name-of-the-container-from-within-the-container/56682693#56682693

**Comment by ateska** [comment]
Closed but evolution needed - see #125
