### ISSUE TITLE
This method is incorrect and it needs to be fixed

### ISSUE THREAD

**Issue by ateska** [TeskaLabs/asab#179]
https://github.com/TeskaLabs/asab/blob/ee3fb38a65e9a5950691b315acbcac3aab3ebb0b/asab/storage/elasticsearch.py#L66

@PremyslCerny 

Issues:

* It is a "get" method but it builds `self.ServerUrls` internally ... and then returns `self.ESURL`
* there is no check for failure in the "else (missing)" branch

**Comment by ateska** [comment]
Please be more specific about *how* it is resolved. @mithunbharadwaj

**Comment by mithunbharadwaj** [comment]
@ateska It was fixed here 
`
https://github.com/TeskaLabs/asab/pull/180`

**Comment by ateska** [comment]
Closed by #180
