### ISSUE TITLE
ZK wrapper Error messages

### ISSUE THREAD

**Issue by eliska-n** [TeskaLabs/asab#234]
https://github.com/TeskaLabs/asab/blob/02e19acbae10450b46a6d5d3361128345204bcb3/asab/zookeeper/wrapper.py#L126

These error messages are very general and do not indicate what is the problem even though they catch specifically NoNode Error. It would be friendly to say that there is no node and pass the path string also into the message.

**Comment by ateska** [comment]
`L.warning("Getting the data from Zookeeper node '{}' failed:{}".format(path, e))`
