### ISSUE TITLE
Open API documentation: Support for regex-based paths

### ISSUE THREAD

**Issue by ateska** [TeskaLabs/asab#249]

**Comment by ateska** [comment]
https://github.com/TeskaLabs/asab/pull/236

**Comment by byewokko** [comment]
Quick fix to prevent critical errors: https://github.com/TeskaLabs/asab/commit/e0c5110c931be37f7780951e1a1ed458368fb276

**Comment by ateska** [comment]
> Quick fix to prevent critical errors: [e0c5110](https://github.com/TeskaLabs/asab/commit/e0c5110c931be37f7780951e1a1ed458368fb276)

Is there anything pending here?

**Comment by byewokko** [comment]
I think with 2cb1e452943d11ac5f3b607964aaa28abeb50745 we can close this.
