### ISSUE TITLE
TODOs in `asab.library` 

### ISSUE THREAD

**Issue by ateska** [TeskaLabs/asab#254]
There are remainders from #239

- [x] `export library` feature on the service level. Only a first library should be exported (or there should be a flag indicating whole/first library content to be exported).
https://github.com/TeskaLabs/asab/pull/260

- [x] Periodical reload of the `.disabled.yaml` https://github.com/TeskaLabs/asab/blob/849fe994fb542fdbefcb95d9cbc40c17186ff657/asab/library/service.py#L83
https://github.com/TeskaLabs/asab/pull/271

- [x] Improved logging in `-v` mode that provides info about where each library provider is connected
https://github.com/TeskaLabs/asab/pull/264

- [x] #284
https://github.com/TeskaLabs/asab/blob/d705cd9bddf05d6c808f59519d7a92d3cd659c82/asab/library/providers/zookeeper.py#L160
- [x] `.read()` method(s) has to be reworked to provide file-based output to avoid loading the whole item content in the memory. It is similar to the export feature.  
https://github.com/TeskaLabs/asab/pull/256

- [x] Support for `zk://./path` form of Zookeeper provider path  - in this case path from zookeeper container and `path` should be concat.ed (NICE TO HAVE feature)
https://github.com/TeskaLabs/asab/pull/261

**Comment by eliska-n** [comment]
Maybe my user experience will be useful:
https://github.com/TeskaLabs/asab/blob/8f79d06b41d11d96bb569a9a5c24797d991ac6a3/asab/library/providers/zookeeper.py#L155
Yes, theres's no version file in my library. Could asab.library make one for me? It would make me very happy. :pig:  And it even periodically tries to read the non-existing version file.

**Comment by ateska** [comment]
> Maybe my user experience will be useful:
> 
> https://github.com/TeskaLabs/asab/blob/8f79d06b41d11d96bb569a9a5c24797d991ac6a3/asab/library/providers/zookeeper.py#L155
> 
> 
> Yes, theres's no version file in my library. Could asab.library make one for me? It would make me very happy. 🐷 And it even periodically tries to read the non-existing version file.
> This is ok? ![image](https://user-images.githubusercontent.com/82450969/179518962-545c4d21-4ed9-4432-883f-0279d3993862.png)

This is intentionally a silent error.
ASAB Library will create `.version.yaml` file.
Reading non-existing version file periodically is acceptable.

**Comment by eliska-n** [comment]
I can add `.version.yaml` into my library or get a bunch of NoNode errors every minute. It is not very silent. Quite hard to accept.

**Comment by ateska** [comment]
> I can add `.version.yaml` into my library or get a bunch of NoNode errors every minute. It is not very silent. Quite hard to accept.

Then the error must be silent.
