### ISSUE TITLE
Alert Service refactoring/updating

### ISSUE THREAD

**Issue by eliska-n** [TeskaLabs/asab#285]
- some seacat copypaste naming
https://github.com/TeskaLabs/asab/blob/5e0777ad74e4407924e1118c392695c828a7c55e/asab/alert.py#L208

- add provider compatible with asab-report microservice
- configuration section name deprecated
- some of the arguments could be default `None`, e.g., tenant id
https://github.com/TeskaLabs/asab/blob/5e0777ad74e4407924e1118c392695c828a7c55e/asab/alert.py#L239
- Appliction also knows the Hostname. What's the difference between 
https://github.com/TeskaLabs/asab/blob/5e0777ad74e4407924e1118c392695c828a7c55e/asab/application.py#L60
and
https://github.com/TeskaLabs/asab/blob/5e0777ad74e4407924e1118c392695c828a7c55e/asab/alert.py#L114
?

- Hostname and...?
https://github.com/TeskaLabs/asab/blob/5e0777ad74e4407924e1118c392695c828a7c55e/asab/alert.py#L186

- 429 - Too Many Requests :) - 8 requests per second based on empirical observation

- to be continued...

**Comment by eliska-n** [comment]
![image](https://user-images.githubusercontent.com/82450969/184636241-c4665a28-88a2-4617-8e3a-a1d36e415ac6.png)


Extra properties = Detail vs. Notes

**Comment by ateska** [comment]
Extra properties should be used for additional info, comments are too noisy and likely cannot be used for categorization.

@eliska-n

**Comment by eliska-n** [comment]
here: https://github.com/TeskaLabs/asab/pull/286/files
