### ISSUE TITLE
Possible unnecessary Docker checking

### ISSUE THREAD

**Issue by mejroslav** [TeskaLabs/asab#367]
https://github.com/TeskaLabs/asab/blob/1175ed1604314d5a6bac5404bf01373e360786dc/asab/api/service.py#L185
@ateska @eliska-n 
Is this really needed?

Also, currently we just check for Docker, but not directly for containers.
https://github.com/TeskaLabs/asab/blob/1175ed1604314d5a6bac5404bf01373e360786dc/asab/docker/__init__.py#L50

**Comment by ateska** [comment]
Yes, I found this as well ... it is useful but it could be only once in the start - to save possibly expensive chek
