### ISSUE TITLE
In-memory StorageService can't be instantiated because of missing implementation of get_by

### ISSUE THREAD

**Issue by mpavelka** [TeskaLabs/asab#52]
`inmemory` is the default storage engine. The following code in `asab/storage/__init__.py`:

```
		if sttype == 'inmemory':
			from .inmemory import StorageService
			self.Service = StorageService(app, "asab.StorageService")
```

fails with  `TypeError: Can't instantiate abstract class StorageService with abstract methods get_by`.

`get_by` must be implemented in `asab/storage/inmemory.py` in `StorageService`

**Comment by SukiCZ** [comment]
Closed in favor 4f5d63356d3d0af5d9e6eef0195cc36e6749d6c7
