### ISSUE TITLE
Limit the check for the extension to last 5 letters

### ISSUE THREAD

**Issue by ateska** [TeskaLabs/asab#557]
The zookeeper library provider detects if the item is a file (not folder) by scanning for "." character.
This MUST be limited to last 5 characters, so that users can put "." in the middle of the long name of the file without an issue.

https://github.com/TeskaLabs/asab/blob/22654362e376df49fdaf55833cd566e26a2c4cea/asab/library/providers/zookeeper.py#L271C4-L271C56

**Comment by ateska** [comment]
@mithunbharadwaj is this still open?

**Comment by mejroslav** [comment]
@mithunbharadwaj Is this one solved already? If so, can you please attach the corresponding MR and close this issue?

**Comment by mithunbharadwaj** [comment]
@mejroslav Solved here  https://github.com/TeskaLabs/asab/pull/558
