### ISSUE TITLE
Extend ASAB Discovery to support application-specific routing

### ISSUE THREAD

**Issue by ateska** [TeskaLabs/asab#559]
# 1) Extend `asab.DiscoveryService` with a discovery cache

Provide a cache of the advertised services organised into following structure:

```json
{
    "instance_id": {
        "lmio-receiver-1": ["http://node1:1234/"],
        "asab-remote-control-1": ["http://node2:5678/"]
        ...
     },
    "service_id": {
        "lmio-receiver": ["http://node1:1234/", "http://node2:1234/", "http://node3:1234/"],
        ...
    },
    "custom1_id": {
        "myid123": ["http://node1: 5678/", "http://node2: 5678/"],
        ...
    },
    "custom2_id": {
        "myid123": ["http://node1: 5678/", "http://node2: 5678/"],
        ...
    },
    ...
}
```

The source of the cache is in the Zookeeper.
Use Zookeeper watcher to keep the cache in-sync (lmio-receiver has this implementation already)

See: https://github.com/TeskaLabs/asab/blob/22654362e376df49fdaf55833cd566e26a2c4cea/asab/api/discovery.py#L39

The user code can use:

1.1) `asab.DiscoveryService.locate()` to get list of URLs:

      DiscoveryService.locate(custom1_id="myid123")

1.2) `asab.DiscoveryService.session()` to get `aiohttp` client: 

    async with session.get("http://myid123.custom1_id.asab/asab/v1/config") as resp:

# 2) How to advertise a **discovery info**

Extend https://github.com/TeskaLabs/asab/blob/22654362e376df49fdaf55833cd566e26a2c4cea/asab/api/service.py#L22

... to enable publishing of advertised data that enables to build cache dictionary from point 1)

```
asab.ApiService.set_discovery({
    "custom1_id": ["myid123", "myid124", myid125"],
    "custom2_id": ["myidABC", "myidDE", myidGHI"],
    "custom3_id": ["mySingleId"],
})
```

`asab.ApiService.set_discovery()` call MUST validate that the input has following type: `{str:[str]}` (dictionary of lists with strings, the dictionary key is string).

This is how a service instance indicates that it can handle given custom ids, so that other microservices can access/delegate requests for them to this microservice.

# 3) How to delegate a request in a web handler

See i.e. `lmio-receiver` how a web handler delegates the call using `aiohttp` client.

**Comment by ateska** [comment]
@eliska-n @PremyslCerny ^

**Comment by eliska-n** [comment]
https://github.com/TeskaLabs/asab/pull/560#issuecomment-2031388377

**Comment by eliska-n** [comment]
this is still open!
