### ISSUE TITLE
I want to be able to extend the AccessLogger in a WebContainer

### ISSUE THREAD

**Issue by mpavelka** [TeskaLabs/asab#59]
In the following code of a `WebContainer`, an `AccessLogger` is provided to `aiohttp.web.AppRunner`:

```
self.WebAppRunner = aiohttp.web.AppRunner(
	self.WebApp,
	handle_signals=False,
	access_log=logging.getLogger(__name__[:__name__.rfind('.')] + '.al'),
	access_log_class=AccessLogger,
)
```
https://github.com/TeskaLabs/asab/blob/0478fcd23f93fc7da42be6820e4a2a132e997b07/asab/web/container.py#L89

As a developer I want to be able to extend the `AccessLogger` so that I can enrich structured data in the access log (for example with an identityId).

**Comment by ateska** [comment]
The ability to specify your own `AccessLogger` class is enough?
@mpavelka

**Comment by ateska** [comment]
It's more about capabilities of aiohttp ... as far as I can tell.
