### ISSUE TITLE
Extract tenant context from request X-Tenant header

### ISSUE THREAD

**Issue by byewokko** [TeskaLabs/asab#591]
- AuthService should extract tenant ID from `X-Tenant` HTTP header.
- Tenant ID in URL parameters will be flagged as deprecated and phased out. It should only be used if there is no `X-Tenant` header.

**Comment by ateska** [comment]
`X-Tenant` must be a preferred way. Once adopted, we will phase-out other possibilities (path & query string) since they are incomplete.
