### ISSUE TITLE
Inotify fails and cannot recover

### ISSUE THREAD

**Issue by eliska-n** [TeskaLabs/asab#607]
https://github.com/TeskaLabs/asab/blob/dea4db4805d287f204792dfcda283c6d8ef5ade6/asab/library/providers/filesystem.py#L204

Míra reported that it happens rather often that inotify is not initialized. 

```
30-Aug-2024 10:18:53.632994 WARNING asab.library.providers.filesystem Subscribing to library changes in filesystem provider is not available. Inotify was not initialized.
```

I can imagine when starting multiple containers, load and iowait get higher and the FD is not assigned..?

There is no retry. 

We make stuff more and more dependent on the subscribe mechanism. Warning is not enough, there must be exception that can be caught in the microservice and microservice can decide what to do with that. 

I'd like to implement some retry mechanism. However, I don't know how to reproduce the issue... don't know how to test whether it works or not... @ateska any ideas?

**Comment by eliska-n** [comment]
parsec only issue

parsec has also issues with connecting to influx (timeout of the requset)

we might be looking for on tick processes

**Comment by ateska** [comment]
Retry will not resolve this issue.
It is likely a side effect of "something broken" in lmio-parsec
