### ISSUE TITLE
Stop event handeled wrong in init time

### ISSUE THREAD

**Issue by awichera** [TeskaLabs/asab#98]
When app.stop is called, before app initialization is done, the stop event is not handeled properly.

**Comment by ateska** [comment]
@awichera - can you please explain what you mean by "not handled properly"?

Provide any kind of log / terminal outputs, code examples, etc.

**Comment by awichera** [comment]
```
import asab


class MyApplication(asab.Application):
    async def initialize(self):
        print("MyApp initialize")
        self.stop()

    async def main(self):
        print("main started")
        # self.stop()

    async def finalize(self):
        print("app finalize")


if __name__ == "__main__":
    app = MyApplication()
    app.run()
```

This application won't stop even though `app.stop` is called.
